[project]
protostar-version = "0.9.1"
lib-path = "lib"
cairo-path = ["lib/cairo_contracts/src", "lib/cairopen_contracts/src"]

[contracts]
ERC721_original = [
    "src/ERC721MintableBurnable.cairo",
]
ERC721_ex03 = [
    "src/ERC721_ex03.cairo",
]

ERC721_ex04 = [
    "src/ERC721_ex04.cairo"
]

ERC721_ex05 = [
    "src/ERC721_ex05.cairo"
]

ERC721_ex07 = [
    "src/ERC721_ex07.cairo"
]

ERC721_Metadata = [
    "src/ERC721_Metadata.cairo"
]

Array = [
    "src/Array.cairo"
]

ShortString = [
    "src/ShortString.cairo"
]