[project]
protostar-version = "0.9.1"
lib-path = "lib"
cairo-path = ["lib/cairo_contracts/src", "lib/cairopen_contracts/src"]

[contracts]
ERC721_original = [
    "src/ERC721MintableBurnable.cairo",
]
ERC721_ex03 = [
    "src/ERC721_ex03.cairo",
]

